name: Deploy documentation

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/deploy-doc.yml
      - foundry.toml

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build the documentation
        run: make doc

      - name: Deploy the documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/book
