name: Quality checks

env:
  FOUNDRY_PROFILE: "ci"

  # This CI workflow is responsible of running the quality tools and building the contracts.
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      repository-projects: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      # required to install our private package from Github Packages
      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install the Node.js dependencies
        run: npm ci

      - name: Run the linter and the formatter in check mode
        run: make quality

      - name: Add lint summary
        run: |
          echo "## Lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Compile the contracts and print their size
        run: make compile-s

      - name: Add compile summary
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
