name: Static analysis

env:
  FOUNDRY_PROFILE: "ci"

# This CI workflow is responsible of running static analysis on the codebase.
on:
  workflow_dispatch:
  pull_request:
    paths:
      - src/**
      - .github/workflows/static-analysis.yml
      - slither.config.json
      - foundry.toml
    branches:
      - main
  push:
    paths:
      - src/**
      - .github/workflows/static-analysis.yml
      - slither.config.json
      - foundry.toml
    branches:
      - main

jobs:
  test:
    # Disable this job for now as Slither does not fully support the combo UDO+IR generation
    # We should monitor the progress of Slither and re-enable this job when it is ready
    # https://github.com/crytic/slither/releases
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run static analysis using Slither
        run: slither . --fail-medium
